### PR TITLE
Sidebar-Disclosuregroup

### LINKED ISSUE #5: Suggestion: DisclosureGroup
Based on the Sidebar tutorial we can add a  DisclosureGroup one.

### PR DESCRIPTION
**Pull request by kicsipixel**
Sidebar DisclosureGroup tutorial added.

### CODE REVIEW

**Comment by wigging** [comment]
It looks like you built the Jekyll site locally and committed the built site files to this pull request. When you build a Jekyll website it creates a `_site` folder. This folder should be ignored by Git and does not need to be pushed to GitHub because GitHub Pages automatically builds the site. Please remove the `_site` folder. This should remove a lot of the files from this pull request.

**Comment by wigging** [comment]
This pull request will automatically close issue #5

**Comment by wigging** [comment]
Why is `webrick` added to the Gemfile? It is not supported by GitHub Pages. See https://pages.github.com/versions/ for supported Jekyll version and other dependencies.

**Comment by kicsipixel** [comment]
https://jekyllrb.com/docs/ but I am going back to 2.7.4 and remove `webrick`.

**Comment by kicsipixel** [comment]
Removed.

**Comment by wigging** [comment]
Also, are you using a `gitignore` file on your computer? Some of these Xcode project files should not be in version control.

**Comment by wigging** [comment]
I just need to add a gitignore file to this repository. I just assume people have one installed on their system.

**Comment by wigging** [comment]
I pulled down your Xcode project but I wasn't able to run it. Did you assign a team member in the signing settings of the Xcode project? If you did, please change that setting to None.

**Comment by kicsipixel** [comment]
> I just need to add a gitignore file to this repository. I just assume people have one installed on their system.

https://github.com/github/gitignore/blob/master/Swift.gitignore

Is this ok or I shall add something?

**Comment by wigging** [comment]
I use https://toptal.com/developers/gitignore to create a single`.gitignore` file for the programming languages and editors that I use. Don't worry about adding one for this pull request. I will add one to the project later.

**Comment by wigging** [comment]
I was able to run the Xcode project. Everything looks good. I have some comments for the documentation:
- Change `disclusuregroup.md` to `sidebar-disclosuregroup.md`
- Change the page title to `title: Sidebar DisclosureGroup`
- Add the page to the bottom of the contents list in the `index.html` file

**Comment by wigging** [comment]
Please fix the spelling of the markdown file. Change `sidebar-disclusuregroup.md` to `sidebar-disclosuregroup.md`. And that should be the last thing to fix.

**Pull request merged**
